[versions]
androidDesugarJdkLibs = "2.1.5"
androidGradlePlugin = "8.12.3"
androidTools = "32.0.0"
androidxActivityKtx = "1.12.2"
androidxAnnotation = "1.9.1"
androidxAppCompat = "1.7.1"
androidXCollectionKtx = "1.5.0"
androidxCore = "1.17.0"
androidxFragment = "1.8.9"
androidxLifecycleRuntimeKtx = "2.10.0"
androidxPreferenceKtx = "1.2.1"
androidxRoom = "2.8.4"
androidxRoomSqlite = "2.6.2"
androidxWorkRuntimeKtx = "2.11.0"
blockhound = "1.0.16.RELEASE"
clikt = "5.1.0"
decourinator = "2.6.1"
geckoview = "147.0.20260116091309"
githubApi = "1.330"
hiddenapibypass = "6.1"
jebrainsAnnotations = "26.0.2-1"
json = "20251224"
jsoup = "1.22.1"
junitJupiterParams = "6.0.2"
kotlin = "2.3.0"
kotlin-ksp = "2.3.4"
kotlinxCoroutines = "1.10.2"
kotlinxDatetime = "0.7.1"
kotlinxHtml = "0.12.0"
kotlinxSerializationJson = "1.10.0"
ktor = "3.4.0"
leakcanary = "2.14"
okhttp = "5.3.2"
rhino = "1.9.0"
r8 = "9.0.32"
shadow = "9.3.1"
slf4jSimple = "2.0.17"
vertx = "5.0.7"
viewbindingpropertydelegate = "1.5.9"
xposed = "82"

[libraries]
android-desugarJdkLibs = { module = "com.android.tools:desugar_jdk_libs_nio", version.ref = "androidDesugarJdkLibs" }
android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "androidGradlePlugin" }
android-tools-common = { module = "com.android.tools:common", version.ref = "androidTools" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "androidxActivityKtx" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidxAnnotation" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidxAppCompat" }
androidx-collection-ktx = { module = "androidx.collection:collection-ktx", version.ref = "androidXCollectionKtx" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "androidxFragment" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidxLifecycleRuntimeKtx" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "androidxPreferenceKtx" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "androidxWorkRuntimeKtx" }
blockhound = { module = "io.projectreactor.tools:blockhound", version.ref = "blockhound" }
clikt = { module = "com.github.ajalt.clikt:clikt", version.ref = "clikt" }
geckoview = { module = "org.mozilla.geckoview:geckoview", version.ref = "geckoview" }
github-api = { module = "org.kohsuke:github-api", version.ref = "githubApi" }
hiddenapibypass = { module = "org.lsposed.hiddenapibypass:hiddenapibypass", version.ref = "hiddenapibypass" }
jebtrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jebrainsAnnotations" }
json = { module = "org.json:json", version.ref = "json" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junitJupiterParams" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin" }
kotlin-ksp-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "kotlin-ksp" }
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinx-html = { module = "org.jetbrains.kotlinx:kotlinx-html", version.ref = "kotlinxHtml" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
ktor-bom = { module = "io.ktor:ktor-bom", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation" }
ktor-server-core-jvm = { module = "io.ktor:ktor-server-core-jvm" }
ktor-server-mustache = { module = "io.ktor:ktor-server-mustache" }
ktor-server-netty-jvm = { module = "io.ktor:ktor-server-netty-jvm" }
ktor-server-status-pages = { module = "io.ktor:ktor-server-status-pages" }
leakcanary-android = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-urlconnection = { module = "com.squareup.okhttp3:okhttp-urlconnection", version.ref = "okhttp" }
r8 = { module = "com.android.tools:r8", version.ref = "r8" }
rhino = { module = "org.mozilla:rhino", version.ref = "rhino" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidxRoom" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidxRoom" }
androidx-sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "androidxRoomSqlite" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4jSimple" }
vertx-lang-kotlin = { module = "io.vertx:vertx-lang-kotlin", version.ref = "vertx" }
vertx-lang-kotlin-coroutines = { module = "io.vertx:vertx-lang-kotlin-coroutines", version.ref = "vertx" }
vertx-web = { module = "io.vertx:vertx-web", version.ref = "vertx" }
viewbindingpropertydelegate-noreflection = { module = "com.github.kirich1409:viewbindingpropertydelegate-noreflection", version.ref = "viewbindingpropertydelegate" }
xposed-api = { module = "de.robv.android.xposed:api", version.ref = "xposed" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
androidx-room = { id = "androidx.room", version.ref = "androidxRoom" }
decourinator = { id = "dev.reformator.stacktracedecoroutinator", version.ref = "decourinator" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "kotlin-ksp" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }

# Plugins defined by this project
buildlogic-android-application = { id = "common.android.application" }
buildlogic-android-library = { id = "common.android.library" }
buildlogic-jvm = { id = "common.jvm" }
buildlogic-kotlin-android = { id = "common.kotlin.android" }
buildlogic-kotlin-jvm = { id = "common.kotlin.jvm" }
buildlogic-kotlin-multiplatform = { id = "common.kotlin.multiplatform" }
